name: Testing

on:
  pull_request:
    branches: [develop]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort==5.10.1
          pip install black==22.6.0
          pip install autoflake==1.4
          pip install mypy==0.942
          pip install types-pytz==2021.3.6
          pip install pydocstyle==6.1.1
      - name: Run isort
        run: |
          python -m isort . --check --profile black
      - name: Run black
        run: |
          python -m black . --check
      - name: Run autoflake
        run: |
          python -m autoflake --exclude=__init__.py \
            --remove-unused-variables --remove-all-unused-imports \
            --in-place --recursive --check .
      - name: Get Modified Files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: space-delimited
      - name: Get Python Files
        id: py_files
        run: |
          files_list=""
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            if [[ ${changed_file} == *.py ]] && [[ ${changed_file} != */migrations/* ]]; then
              files_list+=" ${changed_file}"
            fi
          done
          echo ::set-output name=files::$(echo ${files_list})
      - name: Check typing (MyPy)
        if: steps.py_files.outputs.files != ''
        run: |
          python -m mypy --install-types --non-interactive ${{ steps.py_files.outputs.files }}
          echo "python -m mypy ${{ steps.py_files.outputs.files }}"
          python -m mypy ${{ steps.py_files.outputs.files }}
      - name: Check docstyle (pydocstyle)
        if: steps.py_files.outputs.files != ''
        run: |
          echo "python -m pydocstyle ${{ steps.py_files.outputs.files }}"
          python -m pydocstyle ${{ steps.py_files.outputs.files }}
  image-creation:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache register
        id: cache
        uses: actions/cache@v2
        with:
          path: /tmp/core_image.tar
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile','**/requirements.txt') }}

      - name: Checkout
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Store ENV from AWS SecretManager
        if: steps.cache.outputs.cache-hit != 'true'
        uses: say8425/aws-secrets-manager-actions@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV__AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV__AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.DEV__AWS_REGION_NAME }}
          SECRET_NAME: eva-configurations/testing

      - name: Create Env File
        if: steps.cache.outputs.cache-hit != 'true'
        run: printenv > .env

      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{env.FULL_ECR_REPOSITORY}}:${{env.IMAGE_TAG_NAME}}
          outputs: type=docker,dest=/tmp/core_image.tar
#  tests:
#    runs-on: ubuntu-latest
#    needs: image-creation
#    strategy:
#      matrix:
#        test-path:
#          - tests
#    steps:
#
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Store ENV from AWS SecretManager
#        uses: say8425/aws-secrets-manager-actions@v2
#        with:
#          AWS_ACCESS_KEY_ID: ${{ secrets.DEV__AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV__AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: ${{ secrets.DEV__AWS_REGION_NAME }}
#          SECRET_NAME: eva-configurations/testing
#
#      - name: Create Env File
#        run: printenv > config/.env
#
#      - name: Cache register
#        id: cache
#        uses: actions/cache@v2
#        with:
#          path: /tmp/core_image.tar
#          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile','**/requirements.txt') }}
#
#      - name: Load image
#        run: |
#          docker load --input /tmp/core_image.tar
#
#      - name: up image
#        if: steps.cache.outputs.cache-hit == 'true'
#        run: |
#          docker ps
#          docker-compose -f docker-compose.yaml up -d
#      - name: View logs
#        if: steps.cache.outputs.cache-hit == 'true'
#        run: |
#          docker-compose logs --tail 100
#      - name: Run tests
#        if: steps.cache.outputs.cache-hit == 'true'
#        run: |
#          docker exec intelligence python -m unittest discover -v ${{ matrix.test-path }}